### ISSUE TITLE
建议：新增VideoUtils工具类，同时更新FFMPEG文件到较为新的版本，旧版本scale分辨率调整的功能会用不了

### ISSUE THREAD

**Issue by lynk-coder** [dadiyang/jave#3]
代码如下

public class VideoUtils {
    public static void getVedioThumbnail(File source, File imageTarget, float frameTime) throws IllegalArgumentException, EncoderException {

        if (!source.exists()) {
            throw new IllegalArgumentException("source file does not exists: " + source.getAbsoluteFile());
        }
        Encoder encoder = new IgnoreErrorEncoder();

        MultimediaInfo multimediaInfo = encoder.getInfo(source);
        VideoAttributes video = new VideoAttributes();
        EncodingAttributes attrs = new EncodingAttributes();
        attrs.setFormat("image2");
        attrs.setOffset(frameTime);
        attrs.setDuration(1f);
        attrs.setVideoAttributes(video);
        try {
            encoder.encode(source, imageTarget, attrs);
        } catch (Exception e) {
            throw new IllegalStateException("error: ", e);
        }

    }
}

**Comment by dadiyang** [comment]
方便提一下PR吗？

**Comment by lynk-coder** [comment]
哥们，本机没有弄GIT，不好意思哈。

**Comment by dadiyang** [comment]
好的。我晚点评估一下。感谢！

**Comment by lynk-coder** [comment]
ffmepg可以挖掘的东西非常多，加油哈。尽量做全点，使用的人也会越来越多

**Comment by dadiyang** [comment]
嗯嗯。需要大家共同努力。有需求尽管提。

**Comment by lynk-coder** [comment]
比如修改视频宽高，包里的ffmpeg版本没办法做到伸缩。必须通过width，height去处理，但是width、height必须计算精确，稍微有点偏差都不能生成新的视频。
参考新的option  -vf scale=x:-1

**Comment by dadiyang** [comment]
视频工具类已添加。FFMPEG我这边只使用过音频转换的功能，没用过更多的场景。高版本的包你那里有吗？方便分享一下吗？

**Comment by lynk-coder** [comment]
不好意思，最近回老家办事。具体的文件我这里没有。要花点时间去编译


在2019年03月21日 21:57，Huang Xuyang 写道：

视频工具类已添加。FFMPEG我这边只使用过音频转换的功能，没用过更多的场景。高版本的包你那里有吗？方便分享一下吗？
