### ISSUE TITLE
哥们，麻烦进来一下

### ISSUE THREAD

**Issue by lynk-coder** [dadiyang/jave#4]
方便留个联系方式么，可能你的项目要做一次比较大的调整

**Comment by lynk-coder** [comment]
方便的话私发我  kunloz520@163.com

**Comment by lynk-coder** [comment]
![QQ截图20190408104650](https://user-images.githubusercontent.com/23651124/55695545-a0b65000-59eb-11e9-9afe-d4960aeca290.png)
这个是比较新的版本。可以解决你版本里面关于视频、图片旋转角度的问题，以及AMR信息无法获取的问题

**Comment by lynk-coder** [comment]
并且解决了视频和图片横纵比同时缩放的功能。我这里有相应的编译好的文件，准备发你，在等你联系方式给我

**Comment by dadiyang** [comment]
dadiyang@aliyun.com

**Comment by dadiyang** [comment]
联系方式发你了。

**Comment by lynk-coder** [comment]
邮件已发送。相关的包解压后(bin目录)，都是已经编译好的。

**Comment by lynk-coder** [comment]
win64  macos64  linux64(centos,ubutun) 测试过，都可以使用
手机端的AMR64编译模式的没有去弄。需要的话邮件我
